INSERT INTO iw_library.book (uuid, created_on, description, title) VALUES(UUID(), NOW(), 'DESCRIPTION 1', 'NEW TITLE 1');
INSERT INTO iw_library.book (uuid, created_on, description, title) VALUES(UUID(), NOW(), 'DESCRIPTION 2', 'NEW TITLE 2');
INSERT INTO iw_library.book (uuid, created_on, description, title) VALUES(UUID(), NOW(), 'DESCRIPTION 3', 'NEW TITLE 3');
INSERT INTO iw_library.book (uuid, created_on, description, title) VALUES(UUID(), NOW(), 'DESCRIPTION 4', 'NEW TITLE 4');
INSERT INTO iw_library.book (uuid, created_on, description, title) VALUES(UUID(), NOW(), 'DESCRIPTION 5', 'NEW TITLE 5');
INSERT INTO iw_library.book (uuid, created_on, description, title) VALUES(UUID(), NOW(), 'DESCRIPTION 6', 'NEW TITLE 6');
INSERT INTO iw_library.book (uuid, created_on, description, title) VALUES(UUID(), NOW(), 'DESCRIPTION 7', 'NEW TITLE 7');
INSERT INTO iw_library.book (uuid, created_on, description, title) VALUES(UUID(), NOW(), 'DESCRIPTION 8', 'NEW TITLE 8');
INSERT INTO iw_library.book (uuid, created_on, description, title) VALUES(UUID(), NOW(), 'DESCRIPTION 9', 'NEW TITLE 9');
INSERT INTO iw_library.book (uuid, created_on, description, title) VALUES(UUID(), NOW(), 'DESCRIPTION 10', 'NEW TITLE 10');
INSERT INTO iw_library.book (uuid, created_on, description, title) VALUES(UUID(), NOW(), 'DESCRIPTION 11', 'NEW TITLE 11');
INSERT INTO iw_library.book (uuid, created_on, description, title) VALUES(UUID(), NOW(), 'DESCRIPTION 12', 'NEW TITLE 12');
INSERT INTO iw_library.book (uuid, created_on, description, title) VALUES(UUID(), NOW(), 'DESCRIPTION 13', 'NEW TITLE 13');
INSERT INTO iw_library.book (uuid, created_on, description, title) VALUES(UUID(), NOW(), 'DESCRIPTION 14', 'NEW TITLE 14');
INSERT INTO iw_library.book (uuid, created_on, description, title) VALUES(UUID(), NOW(), 'DESCRIPTION 15', 'NEW TITLE 15');
INSERT INTO iw_library.book (uuid, created_on, description, title) VALUES(UUID(), NOW(), 'DESCRIPTION 16', 'NEW TITLE 16');
INSERT INTO iw_library.book (uuid, created_on, description, title) VALUES(UUID(), NOW(), 'DESCRIPTION 17', 'NEW TITLE 17');
INSERT INTO iw_library.book (uuid, created_on, description, title) VALUES(UUID(), NOW(), 'DESCRIPTION 18', 'NEW TITLE 18');
INSERT INTO iw_library.book (uuid, created_on, description, title) VALUES(UUID(), NOW(), 'DESCRIPTION 19', 'NEW TITLE 19');
INSERT INTO iw_library.book (uuid, created_on, description, title) VALUES(UUID(), NOW(), 'DESCRIPTION 20', 'NEW TITLE 20');
INSERT INTO iw_library.book (uuid, created_on, description, title) VALUES(UUID(), NOW(), 'DESCRIPTION 21', 'NEW TITLE 21');
INSERT INTO iw_library.book (uuid, created_on, description, title) VALUES(UUID(), NOW(), 'DESCRIPTION 22', 'NEW TITLE 22');
INSERT INTO iw_library.book (uuid, created_on, description, title) VALUES(UUID(), NOW(), 'DESCRIPTION 23', 'NEW TITLE 23');
INSERT INTO iw_library.book (uuid, created_on, description, title) VALUES(UUID(), NOW(), 'DESCRIPTION 24', 'NEW TITLE 24');
INSERT INTO iw_library.book (uuid, created_on, description, title) VALUES(UUID(), NOW(), 'DESCRIPTION 25', 'NEW TITLE 25');
INSERT INTO iw_library.author (uuid, created_on, first_name, last_name) VALUES(UUID(), NOW(), 'NAME 1', 'LAST NAME 1');
INSERT INTO iw_library.author (uuid, created_on, first_name, last_name) VALUES(UUID(), NOW(), 'NAME 2', 'LAST NAME 2');
INSERT INTO iw_library.author (uuid, created_on, first_name, last_name) VALUES(UUID(), NOW(), 'NAME 3', 'LAST NAME 3');
INSERT INTO iw_library.author (uuid, created_on, first_name, last_name) VALUES(UUID(), NOW(), 'NAME 4', 'LAST NAME 4');
INSERT INTO iw_library.author (uuid, created_on, first_name, last_name) VALUES(UUID(), NOW(), 'NAME 5', 'LAST NAME 5');
INSERT INTO iw_library.author (uuid, created_on, first_name, last_name) VALUES(UUID(), NOW(), 'NAME 6', 'LAST NAME 6');
INSERT INTO iw_library.author (uuid, created_on, first_name, last_name) VALUES(UUID(), NOW(), 'NAME 7', 'LAST NAME 7');
INSERT INTO iw_library.author (uuid, created_on, first_name, last_name) VALUES(UUID(), NOW(), 'NAME 8', 'LAST NAME 8');
INSERT INTO iw_library.author (uuid, created_on, first_name, last_name) VALUES(UUID(), NOW(), 'NAME 9', 'LAST NAME 9');
INSERT INTO iw_library.author (uuid, created_on, first_name, last_name) VALUES(UUID(), NOW(), 'NAME 10', 'LAST NAME 10');
INSERT INTO iw_library.author (uuid, created_on, first_name, last_name) VALUES(UUID(), NOW(), 'NAME 11', 'LAST NAME 11');
INSERT INTO iw_library.author (uuid, created_on, first_name, last_name) VALUES(UUID(), NOW(), 'NAME 12', 'LAST NAME 12');
INSERT INTO iw_library.author (uuid, created_on, first_name, last_name) VALUES(UUID(), NOW(), 'NAME 13', 'LAST NAME 13');
INSERT INTO iw_library.author (uuid, created_on, first_name, last_name) VALUES(UUID(), NOW(), 'NAME 14', 'LAST NAME 14');
INSERT INTO iw_library.author (uuid, created_on, first_name, last_name) VALUES(UUID(), NOW(), 'NAME 15', 'LAST NAME 15');
INSERT INTO iw_library.author (uuid, created_on, first_name, last_name) VALUES(UUID(), NOW(), 'NAME 16', 'LAST NAME 16');
INSERT INTO iw_library.author (uuid, created_on, first_name, last_name) VALUES(UUID(), NOW(), 'NAME 17', 'LAST NAME 17');
INSERT INTO iw_library.author (uuid, created_on, first_name, last_name) VALUES(UUID(), NOW(), 'NAME 18', 'LAST NAME 18');
INSERT INTO iw_library.author (uuid, created_on, first_name, last_name) VALUES(UUID(), NOW(), 'NAME 19', 'LAST NAME 19');
INSERT INTO iw_library.author (uuid, created_on, first_name, last_name) VALUES(UUID(), NOW(), 'NAME 20', 'LAST NAME 20');
INSERT INTO iw_library.author (uuid, created_on, first_name, last_name) VALUES(UUID(), NOW(), 'NAME 21', 'LAST NAME 21');
INSERT INTO iw_library.author (uuid, created_on, first_name, last_name) VALUES(UUID(), NOW(), 'NAME 22', 'LAST NAME 22');
INSERT INTO iw_library.author (uuid, created_on, first_name, last_name) VALUES(UUID(), NOW(), 'NAME 23', 'LAST NAME 23');
INSERT INTO iw_library.author (uuid, created_on, first_name, last_name) VALUES(UUID(), NOW(), 'NAME 24', 'LAST NAME 24');
INSERT INTO iw_library.author (uuid, created_on, first_name, last_name) VALUES(UUID(), NOW(), 'NAME 25', 'LAST NAME 25');
INSERT INTO iw_library.author_book_mapping (author_id, book_id) VALUES(1, 1);
INSERT INTO iw_library.author_book_mapping (author_id, book_id) VALUES(1, 2);
INSERT INTO iw_library.author_book_mapping (author_id, book_id) VALUES(1, 3);
INSERT INTO iw_library.author_book_mapping (author_id, book_id) VALUES(5, 1);
INSERT INTO iw_library.author_book_mapping (author_id, book_id) VALUES(5, 2);
INSERT INTO iw_library.author_book_mapping (author_id, book_id) VALUES(5, 3);